import { ArrowIcon } from "./pricing-icons";

export function MaterialSection() {
  return (
    <section className="bg-gradient-to-br from-[#071a36] to-[#0a347e] px-5 py-24 text-white sm:px-[6vw] sm:py-28"><div className="mx-auto max-w-[1268px]"><div className="mb-12 grid items-end gap-6 lg:grid-cols-[1.15fr_.85fr] lg:gap-16"><div><span className="mb-4 block text-[10px] font-black tracking-[.19em] text-[#68d4ff]">PHYSICAL PRODUCTS</span><h2 className="text-[39px] font-black leading-[.96] tracking-[-.06em] uppercase sm:text-[54px]">Software subscription and materials stay clearly separated.</h2></div><p className="m-0 text-[15px] leading-7 text-[#c2d2e9]">Builder Assist can also supply project materials. Product charges are quoted separately from the software plans above.</p></div><div className="grid gap-4 lg:grid-cols-2"><article className="grid gap-5 border border-white/20 bg-white/[.07] p-7"><span className="text-[8px] font-black tracking-[.17em] text-[#68d4ff]">TEMPORARY ANTI-CLIMB FENCE</span><div><strong className="block text-[44px] font-black tracking-[-.055em]">$2.50</strong><small className="text-[10px] text-[#acc0dd]">per linear foot / standard</small></div><p className="m-0 text-[11px] text-[#c5d5eb]">Basic privacy mesh: <b className="text-white">+$0.75 per linear foot</b></p><a className="flex w-fit items-center gap-3 border-b-2 border-[#68d4ff] pb-2 text-xs font-black text-[#68d4ff]" href="/index.html#/get-pricing">Price a fence project <ArrowIcon className="h-4 w-4" /></a></article><article className="grid gap-5 border border-white/20 bg-white/[.07] p-7"><span className="text-[8px] font-black tracking-[.17em] text-[#68d4ff]">ENGINEERED HARDWOOD</span><div><strong className="block text-[44px] font-black tracking-[-.055em]">$4.00-$5.75</strong><small className="text-[10px] text-[#acc0dd]">per square foot</small></div><p className="m-0 text-[11px] text-[#c5d5eb]">Final price depends on product, finish, quantity and availability.</p><a className="flex w-fit items-center gap-3 border-b-2 border-[#68d4ff] pb-2 text-xs font-black text-[#68d4ff]" href="/index.html#/get-pricing">Price a flooring project <ArrowIcon className="h-4 w-4" /></a></article></div><p className="mt-5 text-[9px] leading-4 text-[#8fa8ca]">Final material quotes may vary by specifications, quantity, rental term, delivery, installation, site conditions, finish and availability.</p></div></section>
  );
}

export function FaqSection() {
  const questions = [
    ["What happens after the 12-month founding period?", "The founding rate ends after month 12. The company then selects the standard monthly rate or the available annual rate for its plan."],
    ["Are clients, vendors and subcontractors charged as users?", "Core and Complete include unlimited external collaborators. Paid internal-user allowances apply to the people operating Builder Assist inside your company."],
    ["What happens when AI-plan or 3D usage exceeds the allowance?", "Overage pricing is not published on this page. Builder Assist should confirm the applicable upgrade or usage terms in the order form before any overage charge is incurred."],
    ["How much onboarding is included?", "Core includes standard support and setup guides. Complete includes priority onboarding and support. Scale includes a dedicated implementation manager. Enterprise implementation and migration are scoped through sales."],
    ["Is every listed capability and integration available today?", "The plans describe the intended commercial scope. During sales review, Builder Assist should identify each capability as live, beta or planned and include only production-ready commitments in the signed order form."],
    ["Are fencing and flooring included in a software subscription?", "No. Physical products, delivery and installation are quoted separately. The software can help organize and compare project purchasing, but material charges remain separate."],
  ];
  return (
    <section className="mx-auto grid w-full max-w-[1440px] gap-12 px-5 py-24 sm:px-[6vw] sm:py-28 lg:grid-cols-[.68fr_1.32fr] lg:gap-16"><div className="self-start lg:sticky lg:top-28"><span className="mb-4 block text-[10px] font-black tracking-[.19em] text-[#0b4fd3]">PRICING QUESTIONS</span><h2 className="text-[39px] font-black leading-[.96] tracking-[-.06em] text-[#071a36] uppercase sm:text-[54px]">Clear answers before implementation.</h2><p className="mt-6 text-[13px] leading-6 text-[#5e6f89]">Builder Assist should make the commercial terms as understandable as the workflow.</p></div><div className="border-t border-[#d9e5f7]">{questions.map(([question, answer]) => <details key={question} className="border-b border-[#d9e5f7]"><summary className="grid min-h-20 cursor-pointer list-none grid-cols-[1fr_30px] items-center gap-5 py-4 text-sm font-black leading-5 text-[#071a36]"><span>{question}</span><i className="text-2xl not-italic">+</i></summary><p className="-mt-1 mr-10 pb-6 text-xs leading-6 text-[#5e6f89]">{answer}</p></details>)}</div></section>
  );
}
