/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 857a7b94ae43c7e4372eb2ecf9e15982)
interface __BaseEnv_Env {
	CONNECTOR_TOKEN: string;
	OPENTAKEOFF: DurableObjectNamespace<import("./worker").OpenTakeoffContainer>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
		durableNamespaces: "OpenTakeoffContainer";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CONNECTOR_TOKEN">> {}
}
